// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWcjz9nlcZ-LuaUwGP6EfyyniUm-2CRUE',
    appId: '1:889977892944:android:e2bfebff8ee93f1db0e155',
    messagingSenderId: '889977892944',
    projectId: 'abans-online',
    storageBucket: 'abans-online.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADJRNiOx4Tbj9_bussLRw79aIFfXf40ys',
    appId: '1:889977892944:ios:1df06073bf0944f9b0e155',
    messagingSenderId: '889977892944',
    projectId: 'abans-online',
    storageBucket: 'abans-online.firebasestorage.app',
    iosBundleId: 'com.example.abansOnline',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaAwa_4fKFIJ8gz9Ok79gXRf-cg_IQIBU',
    appId: '1:889977892944:web:6c039754db818e7bb0e155',
    messagingSenderId: '889977892944',
    projectId: 'abans-online',
    authDomain: 'abans-online.firebaseapp.com',
    storageBucket: 'abans-online.firebasestorage.app',
    measurementId: 'G-WQ6VYVF7SH',
  );

}

/* 

Platform  Firebase App Id
android   1:889977892944:android:e2bfebff8ee93f1db0e155
ios       1:889977892944:ios:1df06073bf0944f9b0e155

*/